CodebenderBoardBundle:
    resource: "@CodebenderBoardBundle/Resources/config/routing.yml"
    prefix:   /board

CodebenderOwnerBundle:
    resource: "@CodebenderOwnerBundle/Resources/config/routing.yml"
    prefix:   /owner

CodebenderGenericBundle:
    resource: "@CodebenderGenericBundle/Resources/config/routing.yml"
    prefix:   /

CodebenderProjectBundle:
    resource: "@CodebenderProjectBundle/Resources/config/routing.yml"
    prefix:   /project

CodebenderSenderBundle:
    resource: "@CodebenderSenderBundle/Resources/config/routing.yml"
    prefix:   /send

CodebenderUtilitiesBundle:
    resource: "@CodebenderUtilitiesBundle/Resources/config/routing.yml"
    prefix:   /utilities

CodebenderStaticBundle:
    resource: "@CodebenderStaticBundle/Resources/config/routing.yml"
    prefix:   /static

CodebenderUserBundle:
    resource: "@CodebenderUserBundle/Resources/config/routing.yml"
    prefix:   /users


# app/config/routing.yml
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

oneup_uploader:
    resource: .
    type: uploader
